Repository CoJaques/Pongly, pull requests merged in 2023-11, with the labels that each got.

#15 Create own thread for inputHandler and manage input with event
  .gitignore
  src/main/java/pongly/client/CliController.java
  src/main/java/pongly/client/InputHandler.java
  src/main/java/pongly/client/InputManager/InputHandler.java
  src/main/java/pongly/client/InputManager/KeyListener.java
Labels: enhancement

#16 Implement width for paddle
  src/main/java/pongly/Launcher.java
  src/main/java/pongly/client/CliController.java
  src/main/java/pongly/client/DisplayManager.java
  src/main/java/pongly/client/game/Ball.java
  src/main/java/pongly/client/game/DrawableObject.java
  src/main/java/pongly/client/game/Paddle.java
Labels: bug

#5 Add the application protocol diagram
  ApplicationProtocolDiagram/ProtocolDiagram.docx
  ApplicationProtocolDiagram/ProtocolDiagram.pdf
  ApplicationProtocolDiagram/README.md
  ApplicationProtocolDiagram/image-1.png
  ApplicationProtocolDiagram/image.png
Labels: documentation
